name: publics image to DockerHub

on:
  [workflow_dispatch]
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build Image
        run: ./build_to_dockerhub.sh
      
      - name: push imgage to DockerHub
        run:
          docker login -u ybarichev -p ${{secrets.DOCKER_HUB_TOCKEN}}
          docker push ybarichev/my_uav:pure
