name: Build and Push

on:
  [workflow_dispatch]
  
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:

  pure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build Image
        run: docker build -t my-ros-humble:pure -f ./dockerfiles/Dockerfile_pure .
      
      - name: Push Image to DockerHub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker tag my-ros-humble:pure ${{ secrets.DOCKERHUB_USER }}/my-ros-humble:pure
          docker push ${{ secrets.DOCKERHUB_USER }}/my-ros-humble:pure
  
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build Image
        run: docker build -t my-ros-humble:debug -f ./dockerfiles/Dockerfile_debug .
      
      - name: Push Image to DockerHub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker tag my-ros-humble:debug ${{ secrets.DOCKERHUB_USER }}/my-ros-humble:debug
          docker push ${{ secrets.DOCKERHUB_USER }}/my-ros-humble:debug